channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy==1.26.4
  - plotly
  - pytorch==2.2.0
  - pytorch-cuda=11.8
  - tqdm
  - datasets==2.14.0
  - fsspec==2023.9.2
  - einops==0.7.0
  - setuptools==67.7.2
  - wandb
  - huggingface_hub
  - pip
  - pip:
      - git+https://github.com/aip-hd-research/TransformerLens.git
